### ISSUE TITLE
vtam incompatible with cutadapt==3.0

### ISSUE THREAD

**Issue by aitgon** [aitgon/vtam#4]
It looks like vtam and more precisely the "sortreads" is incompatible with the latest cutadapt==3.0. version
Until being fixed, it must be make sure that the cutadapt 2.10 is used.

**Comment by ulysse06** [comment]
Hi,
I tried but couldn't reproduce any error.
On my side it worked with both cutadapt 2.10 and 3.4.

When I run the following command from the tutorial :
`vtam sortreads --fastainfo asper1/run1_mfzr/fastainfo.tsv --fastadir asper1/run1_mfzr/merged --sorteddir asper1/run1_mfzr/sorted -v --log asper1/vtam.log`
it seems to behave as expected.

Could you provide me with more specific information to reproduce the bug?

**Comment by aitgon** [comment]
I have tested and it looks like VTAM is compatible with cutadapt 3.4. Maybe it was just a problem of cutadapt 3.0.
