### ISSUE TITLE
Pb vtam-0.1.21

### ISSUE THREAD

**Issue by meglecz** [aitgon/vtam#6]
After upgrading to vtam-0.1.21 by 
python3 -m pip install --upgrade vtam
there is an error message (python3 -m pip install --upgrade vtam) after issuing any vtam command.

**Comment by aitgon** [comment]
What is the error?

**Comment by meglecz** [comment]
Sorry. I forgot to join the file.

[error_vtam-0.1.21.txt](https://github.com/aitgon/vtam/files/5691521/error_vtam-0.1.21.txt)

**Comment by aitgon** [comment]
I see. It suffices to install tqdm:
pip install tqdm
I will fix for VTAM to do it automatically in the next release.

**Comment by aitgon** [comment]
If not other comments, I close the issue
